TomKlotzPro/openNetwork

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add contribution files for our developers
> chore(md): Add contribution related files

- README.md
| Related Issue     | no
We update the readme with the following template : https://docs.google.com/document/d/1vIDUO5bT7qqScFVhfPPNLvW9Je9fqwSh4_s2iVNs2cI/edit#
We need to deliver a synopsis for the 8th of November 2020.
> Chore(Readme) :update readme with synopsis

- pages/signup.vue
| New feature?      | yes/no    
| Related Issue     | #24  
update length of username which result to fail 
When people want to put a small username it's resulting to fail
> fix: signup username length

- LICENCE
> chore: add Licence

- server/controllers/user.js
- server/services/MailService.js
- server/services/passport.js
Adding process.env to reach environment variables instead of keys
Fix generation of tokens and sending email on production env
> fix: Set correct access to env variables for prod

- components/ProductHero.vue
- pages/projects/_slug.vue
| Related Issue     | 
Update ProductLink to gitLink 
Unable to reach link in producthero
> fix: update productLink to gitLink

- components/shared/Search.vue
| Related Issue     | 
Update css for search dropdown
> fix: add css for mobile

- pages/signup.vue
- server/models/user.js
| Related Issue     | 
Fix username length
> fix: username length

- pages/about.vue
| Related Issue     |
Update picture for sofiane le bg
> fix:update url picture for about page

- components/shared/Search.vue
| New feature?      | no
| Related Issue     |
| Need Doc update   |no
Update search
> fix: update search

- .circleci/config.yml
| Bug fix?          |no
| New feature?      |no    
| Related Issue     | 
Add circle CI
> chore:add circle ci config

- pages/index.vue
| New feature?      | no
| Related Issue     | Fix #42  
Added a conditional chaining for category name
Crashing the app when no categories
> fixing optional variable for category name

- components/shared/Comment.vue
- components/shared/Comments.vue
| Related Issue     | Fix #52  
- Arraged the ui to show a message when comments are absent on a project
- Removed the reply button when user isn't connected
- Minor ui changes 
- Added number of replies per comment
- UI & UX
> FIX - Project page component ui

- pages/confirm.vue
| New feature?      | no   
| Related Issue     | Fix #63 
| Need Doc update   | yes/no
Center a button that was previously misaligned
> fix: Center button in the middle of the email confirmation page

- components/shared/Comments.vue
- pages/blogs/_slug.vue
- server/controllers/blog.js
- server/models/blog.js
- server/routes/blog.js
- store/blog.js
- store/project.js
- utils/functions.js
| New feature?      | yes    
| Related Issue     | Fix #50   
Added comments on blog page
UI/UX
> Fix - added comments on blog page

- components/shared/Footer.vue
- components/shared/Navbar.vue
- pages/about.vue
| New feature?      | no   
Changing location of about page and the current members described in the page.
Also setting the current year date instead of a static year in the footer.
> refactor: Changing location and content of about page

- components/shared/Hero.vue
- components/shared/Navbar.vue
- pages/index.vue
Removed the sample text, and added a better placement for hero and navbar buttons
> chore: change order categories, change button text, and hero text

- pages/index.vue
Bad placement of one text fixed
> chore: fix text layout

- pages/privacy.vue
Add a privacy policy to the platform
> chore: adding the privacy policy of the platform

- components/SelectOption.vue
Minor change : Changing the name of the label inactive for project in the workspace to make it more understandable for users
> refactor: Change name of inactive status for projects
